window.TIKTOK_HISTORY = {
  "2026-05-19": {
    "7d": {
      "scraped_at": "2026-05-19 15:17",
      "start_date": "2026-05-13",
      "end_date": "2026-05-19",
      "summary": {
        "spend": 6521185,
        "revenue": 8264600,
        "roas": 1.27
      },
      "campaigns": [
        {
          "name": "tk_do_spc_23(틱톡)",
          "status": "active",
          "budget": 700000,
          "cpa": 79698,
          "spend": 4702190,
          "revenue": 5425900,
          "roas": 1.15,
          "cpc": 1755,
          "ctr": 2.78,
          "clicks": 2679,
          "impressions": 96349,
          "cpm": 48804,
          "conversions": 59
        },
        {
          "name": "tk_do_spc_21(틱톡)",
          "status": "paused",
          "budget": 320000,
          "cpa": 58677,
          "spend": 1818995,
          "revenue": 2838700,
          "roas": 1.56,
          "cpc": 1300,
          "ctr": 3.21,
          "clicks": 1399,
          "impressions": 43597,
          "cpm": 41723,
          "conversions": 31
        },
        {
          "name": "tk_do_spc_19",
          "status": "paused",
          "budget": 140000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_17",
          "status": "paused",
          "budget": 250000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_15",
          "status": "paused",
          "budget": 450000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_13",
          "status": "paused",
          "budget": 500000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_11(control)",
          "status": "paused",
          "budget": 300000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_09",
          "status": "paused",
          "budget": 700000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_07_카탈로그",
          "status": "paused",
          "budget": 679000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_05_ITR",
          "status": "paused",
          "budget": 715000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        }
      ]
    },
    "14d": {
      "scraped_at": "2026-05-19 15:17",
      "start_date": "2026-05-06",
      "end_date": "2026-05-19",
      "summary": {
        "spend": 12172005,
        "revenue": 17871700,
        "roas": 1.47
      },
      "campaigns": [
        {
          "name": "tk_do_spc_23(틱톡)",
          "status": "active",
          "budget": 700000,
          "cpa": 74878,
          "spend": 8086863,
          "revenue": 11563700,
          "roas": 1.43,
          "cpc": 1691,
          "ctr": 2.29,
          "clicks": 4782,
          "impressions": 209105,
          "cpm": 38674,
          "conversions": 108
        },
        {
          "name": "tk_do_spc_21(틱톡)",
          "status": "paused",
          "budget": 320000,
          "cpa": 57400,
          "spend": 4017991,
          "revenue": 6308000,
          "roas": 1.57,
          "cpc": 1221,
          "ctr": 2.72,
          "clicks": 3291,
          "impressions": 121204,
          "cpm": 33151,
          "conversions": 70
        },
        {
          "name": "tk_do_spc_19",
          "status": "paused",
          "budget": 140000,
          "cpa": 0,
          "spend": 67151,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 483,
          "ctr": 15.6,
          "clicks": 139,
          "impressions": 891,
          "cpm": 75366,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_17",
          "status": "paused",
          "budget": 250000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_15",
          "status": "paused",
          "budget": 450000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_13",
          "status": "paused",
          "budget": 500000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_11(control)",
          "status": "paused",
          "budget": 300000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_09",
          "status": "paused",
          "budget": 700000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_07_카탈로그",
          "status": "paused",
          "budget": 679000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_05_ITR",
          "status": "paused",
          "budget": 715000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        }
      ]
    },
    "30d": {
      "scraped_at": "2026-05-19 15:18",
      "start_date": "2026-04-20",
      "end_date": "2026-05-19",
      "summary": {
        "spend": 16794643,
        "revenue": 25454900,
        "roas": 1.52
      },
      "campaigns": [
        {
          "name": "tk_do_spc_23(틱톡)",
          "status": "active",
          "budget": 700000,
          "cpa": 74878,
          "spend": 8086863,
          "revenue": 11563700,
          "roas": 1.43,
          "cpc": 1691,
          "ctr": 2.29,
          "clicks": 4782,
          "impressions": 209105,
          "cpm": 38674,
          "conversions": 108
        },
        {
          "name": "tk_do_spc_21(틱톡)",
          "status": "paused",
          "budget": 320000,
          "cpa": 53533,
          "spend": 5888652,
          "revenue": 10085100,
          "roas": 1.71,
          "cpc": 525,
          "ctr": 2.27,
          "clicks": 11222,
          "impressions": 494652,
          "cpm": 11905,
          "conversions": 110
        },
        {
          "name": "tk_do_spc_19",
          "status": "paused",
          "budget": 140000,
          "cpa": 67122,
          "spend": 2819128,
          "revenue": 3806100,
          "roas": 1.35,
          "cpc": 995,
          "ctr": 5.28,
          "clicks": 2833,
          "impressions": 53637,
          "cpm": 52559,
          "conversions": 42
        },
        {
          "name": "tk_do_spc_17",
          "status": "paused",
          "budget": 250000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_15",
          "status": "paused",
          "budget": 450000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_13",
          "status": "paused",
          "budget": 500000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "tk_do_spc_11(control)",
          "status": "paused",
          "budget": 300000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_09",
          "status": "paused",
          "budget": 700000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_07_카탈로그",
          "status": "paused",
          "budget": 679000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        },
        {
          "name": "TK_DO_SPC_05_ITR",
          "status": "paused",
          "budget": 715000,
          "cpa": 0,
          "spend": 0,
          "revenue": 0,
          "roas": 0.0,
          "cpc": 0,
          "ctr": 0.0,
          "clicks": 0,
          "impressions": 0,
          "cpm": 0,
          "conversions": 0
        }
      ]
    }
  }
};
